## 分析由LLM生成的Jobs数据集中的混淆变量
## Analyze the confounder generated by LLM for the Jobs dataset

import os
import json
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

def main():
    """
    主函数,加载LLM生成的Jobs数据集,执行统计分析并打印结果。
    Main function: Load LLM-generated Jobs data, perform statistical analysis, and print results.
    """
    # 定义输入文件路径
    json_file_path = 'outcome/1012_outcome/final_data.json'

    print(f"\n{'='*60}")
    print(f"分析文件: {os.path.basename(json_file_path)}")
    print(f"{'='*60}")

    # --- 1. 加载并解析JSON数据 ---
    try:
        with open(json_file_path, 'r', encoding='utf-8') as f:
            json_content = json.load(f)
        
        if not isinstance(json_content, list) or len(json_content) == 0:
            print("错误: JSON格式不正确或为空。")
            return
        
        # 获取第一个(也是唯一一个)数据集
        data_dict = json_content[0]
        
        # 提取元信息
        confounder_name = data_dict.get('confounder_name', 'Unknown')
        confounder_explanation = data_dict.get('confounder_explanation', '')
        distribution_type = data_dict.get('distribution_type', 'Unknown')
        value_description = data_dict.get('value_description', '')
        
        print(f"\n生成的混淆变量信息:")
        print(f"  名称: {confounder_name}")
        print(f"  说明: {confounder_explanation}")
        print(f"  分布类型: {distribution_type}")
        print(f"  值描述: {value_description}")
        
        # 转换为DataFrame
        data_list = data_dict.get('data', [])
        df = pd.DataFrame(data_list)
        
        # 数据清洗:移除不相关的'id'列
        if 'id' in df.columns:
            df = df.drop('id', axis=1)
            print("\n已移除'id'列(不参与分析)")

        print(f"\n数据集维度: {df.shape[0]} 样本 × {df.shape[1]} 变量")
        print(f"变量列表: {list(df.columns)}")
        
        # --- 2. 描述性统计 ---
        print(f"\n{'='*60}")
        print("描述性统计")
        print(f"{'='*60}")
        print(df.describe())
        
        # --- 3. 检查混淆变量与处理/结果的相关性 ---
        print(f"\n{'='*60}")
        print("相关性分析")
        print(f"{'='*60}")
        
        # 计算生成的混淆变量与处理(treat)和结果(re78)的相关性
        if confounder_name in df.columns:
            corr_with_treatment = df[[confounder_name, 'treat']].corr().iloc[0, 1]
            corr_with_outcome = df[[confounder_name, 're78']].corr().iloc[0, 1]
            
            print(f"\n{confounder_name} 与其他变量的相关性:")
            print(f"  与 Treatment (treat): {corr_with_treatment:.4f}")
            print(f"  与 Outcome (re78): {corr_with_outcome:.4f}")
            
            # 完整相关性矩阵
            print(f"\n完整相关性矩阵:")
            corr_matrix = df.corr()
            print(corr_matrix.to_string())
        
        # --- 4. 分组统计 ---
        print(f"\n{'='*60}")
        print("按处理组分组统计")
        print(f"{'='*60}")
        
        # 按treat分组
        if 'treat' in df.columns:
            print("\n按治疗组(treat)分组的统计:")
            grouped_stats = df.groupby('treat').agg({
                're78': ['mean', 'std', 'count'],
                confounder_name: ['mean', 'std'] if confounder_name in df.columns else []
            })
            print(grouped_stats)
            
            # 计算平均处理效应(naive)
            mean_outcome_treated = df[df['treat'] == 1]['re78'].mean()
            mean_outcome_control = df[df['treat'] == 0]['re78'].mean()
            naive_ate = mean_outcome_treated - mean_outcome_control
            
            print(f"\n简单平均处理效应(ATE):")
            print(f"  处理组平均结果: {mean_outcome_treated:.2f}")
            print(f"  对照组平均结果: {mean_outcome_control:.2f}")
            print(f"  差异(ATE): {naive_ate:.2f}")
        
        # --- 5. 数据质量检查 ---
        print(f"\n{'='*60}")
        print("数据质量检查")
        print(f"{'='*60}")
        
        # 检查缺失值
        missing_values = df.isnull().sum()
        if missing_values.sum() > 0:
            print("\n缺失值统计:")
            print(missing_values[missing_values > 0])
        else:
            print("\n✓ 无缺失值")
        
        # --- 6. 保存扩展数据集 ---
        output_csv_path = 'outcome/1012_outcome/jobs_with_confounder.csv'
        df.to_csv(output_csv_path, index=False)
        print(f"\n{'='*60}")
        print(f"✓ 扩展后的数据集已保存到: {output_csv_path}")
        print(f"{'='*60}")
        
    except Exception as e:
        print(f"读取或解析JSON文件时出错: {e}")
        import traceback
        traceback.print_exc()
        return


if __name__ == '__main__':
    main()
